### ISSUE TITLE
Cannot use "moving around " keys

### ISSUE THREAD

**Issue by ilyasmg** [ros-teleop/teleop_twist_keyboard#18]
Hi,
I'm using this package with bebop_autonomy but the moving around keys doesn't work
The other keys work (t,b,q,z,ecc)
I think this might be a problem of the formatting of the commands that are sent when I press the moving keys because I'm also not able to move the drone using rostopic
I used different formats but none works:
rostopic pub /cmd_vel geometry_msgs/Twist "linear: x: 100 y: 100  z: 100 angular: z: 10"
rostopic pub /cmd_vel geometry_msgs/Twist ["100 100 100", "100"]
I tried every format but none works

**Comment by trainman419** [comment]
This doesn't really sound like an issue with `teleop_twist_keyboard` . If you echo the `/cmd_vel` topic and see then linear and angular velocity changing, then it's working, and your problem is probably somewhere else. (this would also explain why using `rostopic pub` does not work).

I would check that you're publishing on the same topic that `bebop_autonomy` is subscribed to. You can see the publishers and subscribers on a topic with `rostopic info /cmd_vel` .

If that shows that `bebop_autonomy` is subscribed and the values are being sent correctly, then the problem is likely with `bebop_autonomy` (or perhaps with your network, if you're running ROS over a network).

If that shows that `bebop_autonomy` is not subscribed, then it probably uses a different topic name (or maybe isn't running).

In either case, I don't know anything about the `bebop_autonomy` package, so there's nothing more I can do to help. I suggest you go ask on answers.ros.org with what you've found, and include a link to this ticket in your question.
